---
# Config file for nightly OCP 4.22
RUN:
  client_version: "4.22.0-0.nightly"
DEPLOYMENT:
  installer_version: "4.22.0-0.nightly"
  terraform_version: "1.0.11"
  # ignition_version can be found here
  # https://docs.openshift.com/container-platform/4.7/post_installation_configuration/machine-configuration-tasks.html#machine-config-overview-post-install-machine-configuration-tasks
  ignition_version: "3.2.0" # TODO: We might want to update to 3.5 or later: https://docs.redhat.com/en/documentation/openshift_container_platform/4.19/html/release_notes/ocp-4-19-release-notes
ENV_DATA:
  vm_template: "rhcos-9.6.20251023-0-vmware.x86_64"
  acm_hub_channel: "release-2.16"
  acm_version: "2.16"
  mce_version: "2.11"
  submariner_version: "0.22.0"
  submariner_image: "quay.io/redhat-user-workloads/submariner-tenant/submariner-fbc-4-21@sha256:3018cfae5a4607b140c58cb38d0b10469c9044207538aa4d0be531d04e8a50af"
  # Below values needs to be changed when acm and submariner are GAed
  submariner_source: "downstream"
  submariner_release_type: "unreleased"
  acm_hub_unreleased: true
  oadp_version: "1.5"
